### ISSUE TITLE
Trying to use gem with Ruby 3.1.0 

### ISSUE THREAD

**Issue by mchilson** [jrobertson/wikisys#1]
I get the following error when I try to initialize a new wiki
wiki = Wikisys::Wiki.new

/home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/mymedia_ftp-0.3.3/lib/mymedia_ftp.rb:5:in `require': cannot load such file -- net/ftp (LoadError)
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/mymedia_ftp-0.3.3/lib/mymedia_ftp.rb:5:in `<top (required)>'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rxfileio-0.2.2/lib/rxfileio.rb:7:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rxfileio-0.2.2/lib/rxfileio.rb:7:in `<top (required)>'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rxfhelper-1.6.3/lib/rxfhelper.rb:9:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rxfhelper-1.6.3/lib/rxfhelper.rb:9:in `<top (required)>'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/jsmenubuilder-0.3.6/lib/jsmenubuilder.rb:6:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/jsmenubuilder-0.3.6/lib/jsmenubuilder.rb:6:in `<top (required)>'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/martile-1.6.2/lib/martile.rb:14:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/martile-1.6.2/lib/martile.rb:14:in `<top (required)>'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/wikisys-0.5.0/lib/wikisys.rb:8:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/wikisys-0.5.0/lib/wikisys.rb:8:in `<top (required)>'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:60:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:55:in `each'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:44:in `each'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:44:in `require'
        from /home/mike/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0/bundler.rb:176:in `require'
        from wiki.rb:3:in `<main>'

**Comment by jrobertson** [comment]
I have pushed a new version of the wikisys gem (0.5.1) in order fix multiple bugs. 

I've never used rbenv but it should work fine if you use RVM. Rbenv is more light weight from what I've read, so I'm wondering if the Ruby built-in net-ftp is included? You could open an IRB session and try `require 'net-ftp'` to find out.

**Comment by mchilson** [comment]
Thanks! Sounds reasonable. I'll give it shot.

**Comment by mchilson** [comment]
That was the issue. thanks for the quick response. Do you have any more documentation on using the gem by chance?

**Comment by jrobertson** [comment]
There is no more documentation unfortunately.  Development reached a certain point where I ran into a couple of issues. Firstly, Wiki entries are stored as Markdown files which need to be managed using an index file. This was duplicating the work I had already done in another project which does more or less the same thing. Secondly, there was a design flaw where a wiki entry appeared under 1 parent heading, but that constrains how wiki entries are referenced.  I've since decided that wiki entries should have no parent headings, but instead, associations through hashtags only.
Wikisys was based on a private development project called _webdoc21_ which was difficult to maintain which is why I created the Wikisys gem with the intention of simplifying the process of creating a wiki system.
I hope to review wikisys again at some point as well as add helpful documentation.
